from __future__ import annotations

from pathlib import Path

import pytest

from app.hook_installer import GitHookInstaller


class TestGitHookInstaller:
    def test_install_hook(self, tmp_path: Path):
        git_dir = tmp_path / ".git" / "hooks"
        git_dir.mkdir(parents=True)
        path = GitHookInstaller.install(tmp_path)
        assert path.exists()
        content = path.read_text()
        assert "Apex Orchestrator" in content
        assert "pre-commit verification" in content

    def test_install_backup_existing(self, tmp_path: Path):
        git_dir = tmp_path / ".git" / "hooks"
        git_dir.mkdir(parents=True)
        existing = git_dir / "pre-commit"
        existing.write_text("# old hook")
        GitHookInstaller.install(tmp_path)
        backup = git_dir / "pre-commit.backup"
        assert backup.exists()
        assert backup.read_text() == "# old hook"

    def test_install_no_git_dir(self, tmp_path: Path):
        with pytest.raises(RuntimeError, match="No .git directory"):
            GitHookInstaller.install(tmp_path)

    def test_uninstall_hook(self, tmp_path: Path):
        git_dir = tmp_path / ".git" / "hooks"
        git_dir.mkdir(parents=True)
        hook = git_dir / "pre-commit"
        hook.write_text("# Auto-generated by Apex Orchestrator")
        assert GitHookInstaller.uninstall(tmp_path) is True
        assert not hook.exists()

    def test_uninstall_no_hook(self, tmp_path: Path):
        git_dir = tmp_path / ".git" / "hooks"
        git_dir.mkdir(parents=True)
        assert GitHookInstaller.uninstall(tmp_path) is False

    def test_uninstall_foreign_hook(self, tmp_path: Path):
        git_dir = tmp_path / ".git" / "hooks"
        git_dir.mkdir(parents=True)
        hook = git_dir / "pre-commit"
        hook.write_text("# some other tool")
        assert GitHookInstaller.uninstall(tmp_path) is False
        assert hook.exists()
