from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.engine.feedback_loop import FeedbackLoop


@dataclass
class ReflectionReport:
    """Report generated by Reflector on agent performance."""

    total_runs: int
    total_actions: int
    success_rate: float
    false_positive_rate: float
    top_false_positives: list[dict[str, Any]] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_runs": self.total_runs,
            "total_actions": self.total_actions,
            "success_rate": self.success_rate,
            "false_positive_rate": self.false_positive_rate,
            "top_false_positives": self.top_false_positives,
            "recommendations": self.recommendations,
        }


class Reflector:
    """Self-reflection engine: analyze past performance to improve future decisions.

    The Reflector:
    1. Reads FeedbackLoop history
    2. Identifies patterns (which issue types are often false positives)
    3. Generates recommendations (skip, lower confidence, escalate)

    Usage:
        reflector = Reflector()
        report = reflector.reflect()
        if report.false_positive_rate > 0.3:
            print("Warning: high false positive rate")
    """

    def __init__(self, feedback: FeedbackLoop | None = None) -> None:
        self.feedback = feedback or FeedbackLoop()

    def reflect(self) -> ReflectionReport:
        """Analyze feedback history and produce reflection report."""
        entries = self.feedback.entries
        if not entries:
            return ReflectionReport(
                total_runs=0,
                total_actions=0,
                success_rate=0.0,
                false_positive_rate=0.0,
                recommendations=["No feedback history yet. Start executing actions to build data."],
            )

        # Group by node_key
        by_node: dict[str, list[Any]] = defaultdict(list)
        for e in entries:
            by_node[e.node_key].append(e)

        total = len(entries)
        successes = sum(1 for e in entries if e.feedback_score > 0)
        failures = sum(1 for e in entries if e.feedback_score < 0)
        success_rate = successes / total if total else 0.0
        fp_rate = failures / total if total else 0.0

        # Find top false positives
        node_scores: dict[str, float] = {}
        for key, history in by_node.items():
            avg = sum(e.feedback_score for e in history) / len(history)
            node_scores[key] = avg

        # Sort by worst average
        worst = sorted(node_scores.items(), key=lambda x: x[1])[:5]
        top_fp = []
        for key, avg in worst:
            if avg < 0:
                top_fp.append({
                    "node_key": key,
                    "average_feedback": round(avg, 2),
                    "occurrences": len(by_node[key]),
                    "recommendation": "Consider skipping or escalating this pattern.",
                })

        recommendations = []
        if fp_rate > 0.3:
            recommendations.append(f"High false positive rate ({fp_rate:.0%}). Consider tightening detection patterns.")
        if success_rate < 0.5:
            recommendations.append(f"Low success rate ({success_rate:.0%}). Review patch quality or test coverage.")
        if not top_fp:
            recommendations.append("All patterns performing well. Maintain current strategy.")

        # Unique runs estimated from timestamp changes (simplistic)
        unique_days = len(set(e.timestamp[:10] for e in entries))

        return ReflectionReport(
            total_runs=max(unique_days, 1),
            total_actions=total,
            success_rate=success_rate,
            false_positive_rate=fp_rate,
            top_false_positives=top_fp,
            recommendations=recommendations,
        )
