from __future__ import annotations

from pathlib import Path


class GitHookInstaller:
    """Install Apex Orchestrator as a git pre-commit hook."""

    _HOOK_TEMPLATE = '''#!/bin/sh
# Auto-generated by Apex Orchestrator hook installer
# Runs quick verification before each commit

echo "[apex-hook] Running pre-commit verification..."
python -m app.cli run --goal="quick verify" --mode=report --target=.
if [ $? -ne 0 ]; then
    echo "[apex-hook] Verification failed. Commit aborted."
    exit 1
fi
echo "[apex-hook] Verification passed."
'''

    @classmethod
    def install(cls, project_root: str | Path, hook_name: str = "pre-commit") -> Path:
        root = Path(project_root)
        git_dir = root / ".git"
        if not git_dir.exists():
            raise RuntimeError(f"No .git directory found in {root}")

        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)

        hook_path = hooks_dir / hook_name

        # If hook already exists, back it up
        if hook_path.exists():
            backup = hook_path.with_suffix(".backup")
            hook_path.rename(backup)

        hook_path.write_text(cls._HOOK_TEMPLATE)
        # Make executable (Unix-like)
        import stat
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        return hook_path

    @classmethod
    def uninstall(cls, project_root: str | Path, hook_name: str = "pre-commit") -> bool:
        root = Path(project_root)
        hook_path = root / ".git" / "hooks" / hook_name
        if not hook_path.exists():
            return False

        # Check if it's our hook
        content = hook_path.read_text()
        if "Apex Orchestrator" not in content:
            return False

        hook_path.unlink()

        # Restore backup if present
        backup = hook_path.with_suffix(".backup")
        if backup.exists():
            backup.rename(hook_path)

        return True
