"""Apex Debug Agent Skill — Integrates Apex Debug static analysis into the swarm.

This agent runs Apex Debug on target code, parses findings, and feeds them
into the orchestrator's epistemic memory and knowledge graph.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any, Optional

from apex_debug.core.finding import Finding, Severity


class ApexDebugAgent:
    """Agent skill that runs Apex Debug analysis on code repositories.

    Usage:
        agent = ApexDebugAgent(project_root="/path/to/code")
        findings = agent.analyze()
        agent.heal(findings)  # Auto-fix where safe
    """

    def __init__(self, project_root: str | Path, min_severity: str = "low") -> None:
        self.project_root = Path(project_root).resolve()
        self.min_severity = min_severity
        self._last_findings: list[Finding] = []

    def analyze(self, target: Optional[str] = None, output_format: str = "json") -> list[Finding]:
        """Run Apex Debug on the project and return findings.

        Args:
            target: Specific file or directory to analyze (default: project_root)
            output_format: json, sarif, or html

        Returns:
            List of Finding objects
        """
        path = target or str(self.project_root)
        cmd = [
            "python", "-m", "apex_debug.cli.app",
            "analyze", path,
            "--min-severity", self.min_severity,
            "--output", output_format,
        ]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=str(self.project_root),
                timeout=120,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            print(f"[ApexDebugAgent] Analysis failed: {e}")
            return []

        if output_format == "json":
            return self._parse_json_output(self.project_root)
        return []

    def _parse_json_output(self, project_root: Path) -> list[Finding]:
        """Parse the report.json generated by Apex Debug."""
        report_file = project_root / "report.json"
        if not report_file.exists():
            return []

        try:
            data = json.loads(report_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return []

        findings: list[Finding] = []
        for item in data.get("findings", []):
            try:
                sev = Severity[item.get("severity", "INFO").upper()]
            except KeyError:
                sev = Severity.INFO

            finding = Finding(
                id=item.get("id", "UNK"),
                file=item.get("file", ""),
                line=item.get("line", 0),
                severity=sev,
                category=item.get("category", "unknown"),
                title=item.get("title", ""),
                message=item.get("message", ""),
                snippet=item.get("snippet", ""),
                confidence=item.get("confidence", 0.5),
            )
            findings.append(finding)

        self._last_findings = findings
        return findings

    def heal(self, findings: Optional[list[Finding]] = None, dry_run: bool = True) -> dict[str, Any]:
        """Auto-fix safe issues using Apex Debug's autofix.

        Args:
            findings: Optional list of findings (uses last analysis if None)
            dry_run: If True, only show what would be fixed

        Returns:
            Summary dict with fixed_files, skipped, errors
        """
        if findings is None:
            findings = self._last_findings

        # Filter to auto-fixable categories
        fixable = [f for f in findings if f.category in ("correctness", "style")]

        if not fixable:
            return {"fixed_files": [], "skipped": 0, "errors": [], "message": "No auto-fixable issues found"}

        cmd = [
            "python", "-m", "apex_debug.cli.app",
            "analyze", str(self.project_root),
            "--min-severity", "info",
            "--category", "correctness",
        ]
        if dry_run:
            cmd.append("--fix-dry-run")
        else:
            cmd.append("--fix")

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        except Exception as e:
            return {"fixed_files": [], "skipped": 0, "errors": [str(e)], "message": "Auto-fix failed"}

        return {
            "fixed_files": [],
            "skipped": len(findings) - len(fixable),
            "errors": [],
            "stdout": result.stdout,
            "stderr": result.stderr,
            "dry_run": dry_run,
        }

    def to_epistemic_claims(self, findings: Optional[list[Finding]] = None) -> list[dict]:
        """Convert findings into epistemic memory claims for the orchestrator.

        Returns:
            List of claim dicts compatible with EpistemicMemory
        """
        if findings is None:
            findings = self._last_findings

        claims: list[dict] = []
        for f in findings:
            claims.append({
                "type": "finding",
                "severity": f.severity.name,
                "category": f.category,
                "title": f.title,
                "message": f.message,
                "location": f.location_str(),
                "confidence": f.confidence,
            })
        return claims
