from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class PRSummaryResult:
    title: str = ""
    body: str = ""
    changed_files: list[str] = field(default_factory=list)
    diff_stat: str = ""
    commit_message: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class PRSummaryGenerator:
    """Generate a structured PR summary from patch context and git state.

    Inputs:
      - changed_files: list of paths touched by the agent
      - patch_plan: original patch plan (task, target files, strategy)
      - task: engineering task context
      - verification: final verification result
      - git_diff_stat: output of git diff --stat
    """

    def generate(
        self,
        project_root: str | Path,
        changed_files: list[str],
        patch_plan: dict[str, Any],
        task: dict[str, Any] | None = None,
        verification: dict[str, Any] | None = None,
        git_diff_stat: str = "",
    ) -> PRSummaryResult:
        task = task or {}
        verification = verification or {}
        title = self._build_title(task, patch_plan)
        body = self._build_body(
            title=title,
            changed_files=changed_files,
            patch_plan=patch_plan,
            task=task,
            verification=verification,
            git_diff_stat=git_diff_stat,
        )
        commit_message = self._build_commit_message(title, changed_files)
        return PRSummaryResult(
            title=title,
            body=body,
            changed_files=list(changed_files),
            diff_stat=git_diff_stat,
            commit_message=commit_message,
        )

    def _build_title(self, task: dict[str, Any], patch_plan: dict[str, Any]) -> str:
        task_title = str(task.get("title", patch_plan.get("title", "Apex Orchestrator patch")))
        # Keep title concise and PR-friendly
        task_title = task_title.strip(".")
        if len(task_title) > 72:
            task_title = task_title[:69] + "..."
        return task_title

    def _build_body(
        self,
        title: str,
        changed_files: list[str],
        patch_plan: dict[str, Any],
        task: dict[str, Any],
        verification: dict[str, Any],
        git_diff_stat: str,
    ) -> str:
        lines: list[str] = []
        lines.append(f"## {title}")
        lines.append("")

        rationale = task.get("rationale", patch_plan.get("change_strategy", ["Automated patch by Apex Orchestrator."]))
        if isinstance(rationale, list):
            rationale = " ".join(rationale)
        lines.append(f"**Rationale:** {rationale}")
        lines.append("")

        if changed_files:
            lines.append("### Changed files")
            for path in changed_files:
                lines.append(f"- `{path}`")
            lines.append("")

        if git_diff_stat.strip():
            lines.append("### Diff stat")
            lines.append("```")
            lines.append(git_diff_stat.strip())
            lines.append("```")
            lines.append("")

        strategy = patch_plan.get("change_strategy", [])
        if strategy:
            lines.append("### Change strategy")
            for item in strategy:
                lines.append(f"- {item}")
            lines.append("")

        verification_ok = verification.get("ok", True)
        if not verification_ok:
            lines.append("### Verification")
            lines.append("- ⚠️  Verification reported issues; review before merge.")
            for key in ("test_summary", "patch_scope", "sensitive_edit"):
                sub = verification.get(key, {})
                if not sub.get("ok", True):
                    lines.append(f"  - `{key}`: {sub.get('reasons', sub.get('error', 'failed'))}")
            lines.append("")
        else:
            lines.append("### Verification")
            lines.append("- ✅ All checks passed.")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Apex Orchestrator*")
        lines.append("")
        return "\n".join(lines)

    def _build_commit_message(self, title: str, changed_files: list[str]) -> str:
        lines = [title, ""]
        if changed_files:
            lines.append("Changed files:")
            for path in changed_files:
                lines.append(f"- {path}")
        return "\n".join(lines)
